<?php if ($this->pageCount): ?>
<div class="paginationControl pagination">
	<ul>
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
	  <li  class="prev"><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
		&larr; Page précédente
	  </a></li>
	<?php else: ?>
	  <li class="prev disabled"><a href="#">&larr; Page précédente</a></li>
	<?php endif; ?>
	 
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
	  <?php if ($page != $this->current): ?>
		<li><a href="<?php echo $this->url(array('page' => $page)); ?>">
			<?php echo $page; ?>
		</a></li>
	  <?php else: ?>
		<li  class="active"><a href="#"><?php echo $page; ?></a></li>
	  <?php endif; ?>
	<?php endforeach; ?>
	 
	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
	 <li class="next"><a  href="<?php echo $this->url(array('page' => $this->next)); ?>">
		Page suivante &rarr;
	  </a></li>
	<?php else: ?>
	  <li  class="next disabled"><a href="#">Page suivante &rarr;</a></li>
	<?php endif; ?>
	</ul>
</div>
<?php endif; ?>
